config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "addresses#new"
end

app/models/address.rb
class Address < ApplicationRecord
  def standarize
    USPS.config.username = Rails.application.credentials.dig(:usps_user_id) # UserID
    usps_address = USPS::Address.new(attributes.except('id', 'standarized', 'created_at', 'updated_at'))
    req = USPS::Request::AddressStandardization.new(usps_address)
    response = req.send!
    resp = response.get(usps_address)
    self.attributes = resp.to_h.except(:name, :return_text)
    self.standarized = true
    self
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  def create
    @address = Address.new(address_params)

    if @address.save
      redirect_to address_url(@address), notice: "Address was successfully created."
    else
      render :new, status: :unprocessable_entity 
    end
  end

  # PATCH/PUT /addresses/1
  def update
    if @address.update(address_params)
      redirect_to address_url(@address), notice: "Address was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /addresses/1
  def destroy
    @address.destroy

    redirect_to addresses_url, notice: "Address was successfully destroyed." 
  end

  private
    def set_address
      @address = Address.find(params[:id])
    end
    
    def address_params
      params.require(:address).permit(:company, :address1, :address2, :city, :state, :zip5, :zip4, :standarized)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p>
    <strong>company name:</strong>
    <%= address.company %>
  </p>

  <p>
    <strong>Address1:</strong>
    <%= address.address1 %>
  </p>

  <p>
    <strong>Address2:</strong>
    <%= address.address2 %>
  </p>

  <p>
    <strong>City:</strong>
    <%= address.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= address.state %>
  </p>

  <p>
    <strong>Zip5:</strong>
    <%= address.zip5 %>
  </p>

  <p>
    <strong>Zip4:</strong>
    <%= address.zip4 %>
  </p>

</div>

app/views/addresses/_form.html.erb
<% readonly ||= false %>
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :company, style: "display: block", class: "form-label" %>
    <%= form.text_field :company, readonly: readonly, class: "form-control" %>
  </div>

  <div>
    <%= form.label :address1, style: "display: block" %>
    <%= form.text_field :address1, readonly: readonly, class: "form-control" %>
  </div>

  <div>
    <%= form.label :address2, style: "display: block", class: "form-label" %>
    <%= form.text_field :address2, readonly: readonly, class: "form-control" %>
  </div>

  <div>
    <%= form.label :city, style: "display: block", class: "form-label" %>
    <%= form.text_field :city, readonly: readonly, class: "form-control" %>
  </div>

  <div>
    <%= form.label :state, style: "display: block", class: "form-label" %>
    <%= form.text_field :state, readonly: readonly, class: "form-control" %>
  </div>

  <div>
    <%= form.label :zip5, style: "display: block", class: "form-label" %>
    <%= form.text_field :zip5, readonly: readonly, class: "form-control" %>
  </div>

  <div>
    <%= form.label :zip4, style: "display: block", class: "form-label" %>
    <%= form.text_field :zip4, readonly: readonly, class: "form-control" %>
  </div>

  <div>
    <%= form.hidden_field :standarized %>
  </div>
  <hr class="my-4">
  <div>
    <%= form.submit "Update#{ ' to Standarized Address' if readonly }", class: "w-100 btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h4>Editing address</h4>

<%= render "form", address: @address %>

<br>

<hr class="my-4">
<div class="btn-group">
  <%= link_to "Show this address", @address, class: "btn btn-secondary" %>
  <%= link_to "Back to addresses", addresses_path, class: "btn btn-secondary" %>
</div>

app/views/addresses/index.html.erb
<p style="color: green"><%= notice %></p>

<h4>Addresses</h4>

<%= link_to "New address", new_address_path, class: "btn btn-primary" %>

<% if @addresses.any? %>
  <table id="addresses" class="table">
    <thead>
        <th></th>
        <th>company</th>
        <th>address1</th>
        <th>address2</th>
        <th>city</th>
        <th>state</th>
        <th>zip5</th>
        <th>zip4</th>
        <th></th>
    </thead>
    <% @addresses.each do |address| %>
      <tr>
        <td>
          <%= button_to address, method: :delete, title: "Destroy this address", class: "btn btn-danger" do %>
            <i class="bi bi-x"></i>
          <% end %>
        </td>
        <td><%= address.company %></td>
        <td><%= address.address1 %></td>
        <td><%= address.address2 %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.zip5 %></td>
        <td><%= address.zip4 %></td>
        <td>
          <%= link_to address, title: "Show this address",  class: "btn btn-secondary" do %>
            <i class="bi bi-eye"></i>
          <% end %>
          <%= link_to edit_address_path(address), title: "Edit this address", class: "btn btn-secondary" do %>
            <i class="bi bi-pencil"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/addresses/new.html.erb
<h4>New address</h4>

<%= render "form", address: @address %>

<br>

<hr class="my-4">
<div>
  <%= link_to "<< Back to addresses", addresses_path, class: "btn btn-secondary" %>
</div>

app/views/addresses/show.html.erb
<div class="row">
  <div class="col">
    <h4>Address</h4>
    <p style="color: green"><%= notice %></p>

    <%= render @address %>
    <% unless @address.standarized? %>
      <hr class="my-4">
      <%= link_to "Keep address as entered", addresses_path, class: 'w-100 btn btn-primary btn-lg' %>
    <% end %>
  </div>
  <div class="col">
    <% unless @address.standarized? %>
      <h4>Standarized Address (USPS Service)</h4>
      <%= render partial: "form", locals: { address: @address.standarize, readonly: true } %>
    <% end %>
  </div>
</div>
<hr class="my-4">
<%= link_to "Back to addresses", addresses_path, class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-light">
    <main class="container py-5">
      <%= yield %>
    <main>
  </body>
</html>